vrook_blog/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'
urlpatterns = [
    path('register/', views.register_view, name="register"),
    path('login/', views.login_view, name="login"),
    path('profile/', views.profile, name='profile'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
]

vrook_blog/articles/urls.py
from django.urls import path
from . import views

app_name='articles'
urlpatterns = [
    path('',views.articles,name="list"),
    path('create/', views.article_create, name="create"),
    path('<slug:slug>/', views.article_detail,name="details"),
]
# This has been significantly changed in Django 3, this could be done like this:
# path('<slug:slug>/', views.article_detail),
# where the first slug "<slug" is the type of the passed parameter which is a slug in our case, and the second slug ":slug>" is the name of the parameter which could be any name; "abc", "the_slug", etc.
# If you still insist to use regex then there is one thing to change; the method name instead of "url" use "re_path":
# re_path(r'^(?P<slug>[\w-]+)/$', views.article_detail),

vrook_blog/vrook_blog/urls.py
# from django.contrib import admin
from django.urls import path, include
# from . import views, settings
# from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# from django.conf.urls.static import static
# from django.conf import settings

from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('about/', views.about,name='about'),
    path('contact/', views.contact,name='contact'),
    path('tos/', views.tos,name='tos'),
    path('privacy/', views.privacy,name='privacy'),
    path('team/', views.team,name='team'),
    path('',  article_views.articles, name="home"),
]

# urlpatterns+=staticfiles_urlpatterns()
if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vrook_blog/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self):
        super().save()

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

vrook_blog/articles/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User


# Create your models here.

# run below commands after writing model code
# python manage.py makemigrations
# python manage.py migrate

class Articles(models.Model):
    title = models.CharField(max_length=250)
    slug = models.SlugField()
    # body=models.TextField()
    body = RichTextField(blank=True, null=True)
    date = models.DateTimeField(auto_now_add=True)
    thumbnail = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User, default=None, on_delete=models.DO_NOTHING, )

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + '..(continued!)'

vrook_blog/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

vrook_blog/articles/forms.py
from django import forms
from . import models


class CreateArticles(forms.ModelForm):
    class Meta:
        model = models.Articles
        fields = ['title', 'slug', 'body', 'thumbnail']

vrook_blog/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib import messages
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from django.contrib.auth.decorators import login_required


# Create your views here.
def register_view(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            # login the user
            user = form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created for {username}!')
            login(request, user)
            return redirect('articles:list')
    else:
        form = UserRegisterForm()
    return render(request, 'accounts/signup.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # login the user
            user = form.get_user()
            login(request, user)
            return redirect('articles:list')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})


@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Profile updated successfully!')
            return redirect('accounts:profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    content = {
        'u_form': u_form,
        'p_form': p_form
    }
    return render(request, 'accounts/profile.html', content)

vrook_blog/articles/views.py
from django.shortcuts import render, redirect
from .models import Articles
from django.http import HttpResponse
from django.contrib.admin.views.decorators import staff_member_required
from . import forms


# Create your views here.
def articles(request):
    articles = Articles.objects.all().order_by('-date')
    return render(request, 'articles/articles.html', {'articles': articles})


def article_detail(request, slug):
    # return HttpResponse(slug)
    article = Articles.objects.get(slug=slug)
    return render(request, 'articles/article_detail.html', {'article': article})


@staff_member_required()
def article_create(request):
    if request.method == 'POST':
        form = forms.CreateArticles(request.POST, request.FILES)
        if form.is_valid():
            # saving to db with author attached
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('articles:list')
    else:
        form = forms.CreateArticles()
    return render(request, 'articles/article_create.html', {'form': form})

vrook_blog/vrook_blog/views.py
from django.http import HttpResponse
from django.shortcuts import render


def homepage(request):
    # return HttpResponse('homepage')
    return render(request, 'homepage.html')


def about(request):
    return render(request, 'about.html')


def contact(request):
    return render(request, 'contact.html')


def tos(request):
    return render(request, 'tos.html')


def privacy(request):
    return render(request, 'privacy.html')


def team(request):
    return render(request, 'team.html')

vrook_blog/accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}
{% load crispy_forms_tags %}
{% block content %}
     <div class="content-section">
        <form method="POST" action="/accounts/login/">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Login</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Need An Account? <a class="ml-2" href="{% url 'accounts:register' %}">Sign Up Now!</a>
            </small>
        </div>
    </div>
{% endblock%}

vrook_blog/accounts/templates/accounts/logout.html
{% extends 'base_layout.html' %}
{% block content %}
    <h2>Logged Out</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
         <a  href="{% url 'accounts:login' %}">Login Again!</a>
        </small>
    </div>

{% endblock%}

vrook_blog/accounts/templates/accounts/profile.html
{% extends 'base_layout.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
        <div class="media-body">
          <h2 class="account-heading">{{ user.username }}</h2>
          <p class="text-secondary">{{ user.email }}</p>
        </div>
      </div>
      <!-- FORM HERE -->
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Profile Info</legend>
                {{ u_form|crispy }}
                {{ p_form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Update</button>
            </div>
        </form>
    </div>
{% endblock content %}

vrook_blog/accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}
{% load crispy_forms_tags %}
{% block content %}
     <div class="content-section">
        <form method="POST" action="/accounts/register/">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Us Today</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign Up</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already Have An Account? <a class="ml-2" href="{% url 'accounts:login' %}">Login</a>
            </small>
        </div>
    </div>
{% endblock%}

vrook_blog/articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="create-article">
        <h1><strong>Create a Blog post</strong> </h1>
        <form class="site-form" method="post" action="{% url 'articles:create' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media|safe }}
            {{ form|crispy }}
            <input type="submit" value="Create">
        </form>
    </div>
{% endblock%}

vrook_blog/articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}
    <div class="article-detail">
        <img src="{{article.thumbnail.url}}">
        <h2>{{ article.title }}</h2>
        <p>{{ article.body|safe }}</p>
        <p>This Article is posted by-<strong>{{ article.author }}</strong></p>
        <p>{{ article.date|date:"F d,Y"  }}</p>

    </div>
{% endblock%}

vrook_blog/articles/templates/articles/articles.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Vrook Blog Posts</h1>
    <div class="row">
    <div class="col-md-8 articles">
        {% for article in articles %}
            <article class="media content-section">
                <img class="rounded-circle article-img" src="{{ article.author.profile.image.url }}">
              <div class="media-body">
                <div class="article-metadata">
                  <a class="mr-2" href="#">{{ article.author }}</a>
                  <small class="text-muted">{{ article.date|date:"F d,Y" }}</small>
                </div>
                <h2><a class="article-title" href="{% url 'articles:details' slug=article.slug %}">{{ article.title  }}</a></h2>
                <p class="article-content">{{ article.snippet|safe }}</p>
                <a class="btn btn-outline-info" href="{% url 'articles:details' slug=article.slug %}" role="button">Read More</a>
              </div>
            </article>
        {% endfor %}
    </div>

    <div class="col-md-4">
          <div class="content-section">
            <h3>Our New Blog Page</h3>
                <p class='text-muted'>You can put any information here you'd like.
                  <ul class="list-group">
                    <li class="list-group-item list-group-item-light">Latest Posts</li>
                    <li class="list-group-item list-group-item-light">Announcements</li>
                    <li class="list-group-item list-group-item-light">Calendars</li>
                    <li class="list-group-item list-group-item-light">etc</li>
                  </ul>
                </p>
          </div>
    </div>
    </div>
{% endblock%}

vrook_blog/templates/about.html
{% extends 'base_layout.html' %}

{% block content %}

<h1 class="text-center"><strong> About Vrook </strong></h1>
    <div id="about_nav">
        <p><strong>VROOK</strong> – founded by a group of Entrepreneurial Engineers, is India’s first immersive
          learning platform for Engineering and Higher education. Launched in 2017, VROOK
          is helping students across engineering streams with highly visualized learning
          programs to transform their ability to understand and conceptualize engineering
          subjects..</p>

        <p>With over 5 years of experience in understanding the higher education sector, the
          team has evolved with the market to meet the growing needs of the higher education
          industry. With a diverse team comprising of passionate founders and committed
          employees, VROOK believes in inspiring students to learn and acquire skill sets
          which can empower them for a better future. We at VROOK, are guided by world
          class mentors who believe in our journey. </p>

        <p>Each course consists of subject matter experts and content specialists who belong to
          faculty departments of reputed institutes. They are involved in curating the content of
          the courses provided in the learning platform. VROOK is a learning experience!</p>

        <p>The world of reality has its limit. But, the world of imagination is boundless. Join us in
          our endeavour, as we explore the world of education technology and move towards
          enabling students’ equal opportunity to dream and learn to the best of their potential.</p>
    </div>
{% endblock%}

vrook_blog/templates/base_layout.html
{% load static %}
<html>
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <title>Vrook Blog</title>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
    </head>
    <body>
        <header class="site-header">
          <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
            <div class="container">
              <a class="navbar-brand mr-4" href="{% url 'home' %}"><img src="{% static 'logo.png' %}"></a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                   <a class="nav-item nav-link" href="{% url 'articles:list' %}">Articles</a>
                   <a class="nav-item nav-link" href="{% url 'team' %}">Vrook Team</a>
                  <a class="nav-item nav-link" href="{% url 'about' %}">About</a>
                  <a class="nav-item nav-link" href="{% url 'contact' %}">Contact Us</a>
                </div>
                <!-- Navbar Right Side -->
                <div class="navbar-nav">
                    {% if user.is_authenticated %}
                      <a class="nav-item nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                      <a class="nav-item nav-link" href="{% url 'articles:create' %}">Add Article</a>
                      <a class="nav-item nav-link" href="{% url 'accounts:profile' %}">My Profile</a>
                    {% else %}
                      <a class="nav-item nav-link" href="{% url 'accounts:login' %}">Login</a>
                      <a class="nav-item nav-link" href="{% url 'accounts:register' %}">Register</a>
                    {% endif %}
                </div>
              </div>
            </div>
          </nav>
        </header>

        <main role="main" class="container" id="body">
          <div class="row">
            <div class="col-md-12">
                {% if messages %}
                    {% for message in messages %}
                      <div class="alert alert-{{ message.tags }}">
                        {{ message }}
                      </div>
                    {% endfor %}
                {% endif %}
              {% block content %}{% endblock %}
            </div>
          </div>
        </main>
        <footer class="p-2 mb-0  " id="footer-bg">
            <div class=".container">
              <div class="row">
                <div class="col-sm-6 col-md-3" >
                    <a  href="{% url 'home' %}"><img src="{% static 'vrook_logo.png' %}"></a>
                </div>

                <div class="col-sm-6 col-md-4 text-center text-md-left" >
                  <h2><span class="d-flex justify-content-center  text-dark" id="about"><strong> About the company</strong></span></h2>
                  <p class="text-white " id="about-content">Vrook believes in inspiring students to learn and acquire skill sets which can empower them for a better future.</p>
                </div>

                <div class="col-sm-12 col-md-5 ">
                  <h2><span class="d-flex justify-content-center  text-dark" id="connect-us"><strong>Connect With Us </strong></span></h2>
                  <div class="d-flex justify-content-center" id="icons">
                    <p>
                        <a  href=https://www.facebook.com/vrook.co target="_blank"> <i class="fa fa-facebook fa-2x mx-3"></i></a>
                        <a  href=https://twitter.com/vrook_co target="_blank"> <i class="fa fa-twitter fa-2x mx-3"></i></a>
                        <a  href=https://www.instagram.com/vrook.co/ target="_blank"> <i class="fa fa-instagram fa-2x mx-3"></i></a>
                        <a  href=https://www.linkedin.com/company/booksbeka-online-solutions-private-limited target="_blank"> <i class="fa fa-linkedin fa-2x mx-3"></i></a>
                        <a  href=https://www.youtube.com/channel/UCv-OBAd6y1GeNK1Qx1aaJjg target="_blank"> <i class="fa fa-youtube fa-2x mx-3"></i></a>
                    </p>
                  </div>
                </div>
              </div>

              <div class="d-flex justify-content-center " id="navlinks" >
                <div>
                  <p>
                    `<a class="text-white"  href="/about">About</a>
                      |
                      <a class="text-white"  href="/contact">Contact</a>
                      |
                      <a class="text-white" href="/tos">Terms of service</a>
                      |
                      <a class="text-white" href="/privacy">Privacy Policy</a>
                    </p>
                </div>
              </div>

              <div class="col d-flex justify-content-center text-white ">
                <p> © <a class="text-white"  href="https://vrook.co/"  target="_blank" > BOOKSBEKA </a>ONLINE SOLUTIONS PVT LTD. ALL RIGHTS RESERVED</p>
              </div>
            </div>
        </footer>

        <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

vrook_blog/templates/contact.html
{% extends 'base_layout.html' %}

{% block content %}

 <div class="container">

   <div class="row">

    <div class="col-xl-8 offset-xl-2 py-5" id="contactform">
      <div id="contacttitle">
        <h1><strong>Contact Form</strong></h1>
      </div>
        <form id="contact-form" method="POST" action="https://formsubmit.co/info@vrook.co" role="form">
          <input type="hidden" name="_template" value="table">

          <label><strong>Full Name</strong></label>
          <input type="text" id="fname" name="Full_Name" placeholder="Your name..">

          <label><strong>Email</strong></label>
          <input type="email" name="email" placeholder="Email Address">

          <label><strong>Phone Number</strong></label>
          <input type="text" id="lname" name="Number" placeholder="Your Phone Number..">

          <label for="subject"><strong>Subject</strong></label>
            <select id="subject" name="subject">
              <option value="login/register_related">login/register related</option>
              <option value="Course_related">Course related</option>
              <option value="other">Others</option>
            </select>

          <label><strong>Message</strong></label>
          <textarea id="subject" name="message" placeholder="Write something.." style="height:200px"></textarea>

          <input type="submit"  value="Submit">

        </form>

      </div>

    </div>

  </div>

{% endblock%}

vrook_blog/templates/homepage.html
<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <title>Vrook blog</title>-->
<!--</head>-->
<!--<body>-->
<!--    <h1>Vrook blog</h1>-->
<!--    <p>VROOK believes in inspiring students to learn and acquire skill sets which can empower them for a better future.</p>-->
<!--</body>-->
<!--</html>-->

{% extends 'base_layout.html' %}

{% block content %}
    <h1>Vrook blog</h1>
    <p>VROOK believes in inspiring students to learn and acquire skill sets which can empower them for a better future.</p>
{% endblock%}